version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s %(levelname)s %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

#a run will auto-create logs/out_<time>.txt; we don't need 'file' handlers

loggers:
    pdr:
        level: INFO
        handlers: [console]
        propagate: no

    sim_engine:
        level: INFO

    predictoor_agent:
        level: INFO

    trader_agent:
        level: INFO

# grep -r getLogger pdr_backend/* |grep -v Binary| sed -e 's/.*getLogger(\"//' | sed -e 's/\".*//' | uniq | tr -t

root:
    level: INFO
    handlers: [console]
